In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/datasets/yasserh/titanic-dataset

# Part A: Understanding the Dataset

In [3]:
import numpy as np
import pandas as pd

In [4]:
#1. Load the Titanic dataset.
df = pd.read_csv('/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
#2. Display the first 10 rows.
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [6]:
#3. Display the last 10 rows.
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [7]:
#4. Find the number of rows and columns.
df.shape

(891, 12)

In [8]:
#5. Display the column names.
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
#6. Display the data types of all columns.
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
# 7. Generate summary statistics of numerical columns.
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
#8. Generate summary statistics of categorical columns.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [12]:
#9. Display random 15 records.
df.sample(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
611,612,0,3,"Jardin, Mr. Jose Neto",male,NaN,0,0,SOTON/O.Q. 3101305,7.0500,NaN,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...",female,33.0,3,0,3101278,15.8500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.0,0,0,343276,8.0500,NaN,S
243,244,0,3,"Maenpaa, Mr. Matti Alexanteri",male,22.0,0,0,STON/O 2. 3101275,7.1250,NaN,S
50,51,0,3,"Panula, Master. Juha Niilo",male,7.0,4,1,3101295,39.6875,NaN,S
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
454,455,0,3,"Peduzzi, Mr. Joseph",male,NaN,0,0,A/5 2817,8.0500,NaN,S
465,466,0,3,"Goncalves, Mr. Manuel Estanslas",male,38.0,0,0,SOTON/O.Q. 3101306,7.0500,NaN,S
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
123,124,1,2,"Webber, Miss. Susan",female,32.5,0,0,27267,13.0000,E101,S
452,453,0,1,"Foreman, Mr. Benjamin Laventall",male,30.0,0,0,113051,27.7500,C111,C
122,123,0,2,"Nasser, Mr. Nicholas",male,32.5,1,0,237736,30.0708,NaN,C
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
212,213,0,3,"Perkin, Mr. John Henry",male,22.0,0,0,A/5 21174,7.2500,NaN,S

In [13]:
#10. Identify numerical and categorical columns.
num_col = df.select_dtypes(exclude = 'object').columns
cate_col = df.select_dtypes(include = 'object').columns

In [14]:
print('numerical columns:',num_col)
print('categorical columns:',cate_col)

numerical columns: Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')
categorical columns: Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

# Part B: Data Selection & Filtering

In [15]:
#1. Display only the Name column.
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [16]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
#2. Display Name , Age , and Fare .
df[['Name','Age','Fare']]

                                                  Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                               Heikkinen, Miss. Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
886                              Montvila, Rev. Juozas  27.0  13.0000
887                       Graham, Miss. Margaret Edith  19.0  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  23.4500
889                              Behr, Mr. Karl Howell  26.0  30.0000
890                                Dooley, Mr. Patrick  32.0   7.7500

[891 rows x 3 columns]

In [18]:
#3. Display passengers whose age is greater than 40.
df[df['Age']>40]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [19]:
# 4. Display female passengers.
df[df['Sex']=='female']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [20]:
#5. Display passengers who survived.
df[df['Survived']==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [21]:
#6. Display passengers who paid a fare greater than 100.
df[df['Fare']> 100]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C
215,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C
258,259,1,1,"Ward, Miss. Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C
325,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S
393,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S
537,538,1,1,"LeRoy, Miss. Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C
708,709,1,1,"Cleaver, Miss. Alice",female,22.00,0,0,113781,151.5500,NaN,S
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C
730,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S
802,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S

In [22]:
#7. Display passengers traveling in First Class.
df[df['Pclass']==1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [23]:
#8. Display passengers whose age is between 20 and 40.
df[(df['Age']>= 20) & (df['Age']<=40)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [24]:
#9. Display passengers who embarked from Southampton ( S ).
df[df['Embarked']=='S']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [25]:
#10. Display passengers who are younger than 18.
df[df['Age']>18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# Part C: Data Cleaning

In [26]:
# The company has noticed missing and inconsistent information in the dataset.

In [27]:
# 1. Find the missing values in each column.
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [28]:
#2. Identify the column with the highest number of missing values.
df.isna().sum().idxmax()

'Cabin'

In [29]:
#3. Display all rows where Age is missing.
df[df['Age'].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [30]:
#4. Display all rows where Cabin is missing.
df[df['Cabin'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [31]:
#5. Remove rows where Age is missing.
df.dropna(subset =['Age'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [32]:
#6. Fill missing Age values using the median.
df['Age'] = df['Age'].fillna(df['Age'].median)
df['Age']

0                                                   22.0
1                                                   38.0
2                                                   26.0
3                                                   35.0
4                                                   35.0
                             ...
886                                                 27.0
887                                                 19.0
888    <bound method Series.median of 0      22.0\n1 ...
889                                                 26.0
890                                                 32.0
Name: Age, Length: 891, dtype: object

In [33]:
# 7. Fill missing Embarked values using the mode.
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode)
df['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [34]:
df = pd.read_csv('/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv')

In [35]:
#8. Replace missing Cabin values with "Unknown" .
df['Cabin'].isna().sum()
df['Cabin'] = df['Cabin'].fillna('Unknown')
df['Cabin']

0      Unknown
1          C85
2      Unknown
3         C123
4      Unknown
        ...
886    Unknown
887        B42
888    Unknown
889       C148
890    Unknown
Name: Cabin, Length: 891, dtype: object

In [36]:
#9. Replace:
# male → Male
# female → Female

df['Sex'] = df['Sex'].replace({'male': 'Male',
                               'female':'Female'})
df['Sex']

0        Male
1      Female
2      Female
3      Female
4        Male
        ...
886      Male
887    Female
888    Female
889      Male
890      Male
Name: Sex, Length: 891, dtype: object

In [37]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,13.0000,Unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,23.4500,Unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,7.7500,Unknown,Q

In [38]:
# 10. Rename:

# Pclass → Passenger_Class
# Fare → Ticket_Price

df = df.rename(columns ={
    'Pclass': 'Passenger_Class',
    'Fare': 'Ticket_Price'
})

df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,13.0000,Unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,23.4500,Unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,7.7500,Unknown,Q

In [39]:
#11. Check whether duplicate records exist.
df.duplicated().sum()

np.int64(0)

In [40]:
#12. Remove duplicate records.
df.drop_duplicates()

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,Unknown,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,13.0000,Unknown,S
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,23.4500,Unknown,S
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,7.7500,Unknown,Q

In [41]:
#13. Verify that duplicates have been removed.
df.duplicated().sum()

np.int64(0)

In [42]:
#14. Save the cleaned dataset as Titanic_Cleaned.csv.
df.to_csv('Titanic_Cleaned.csv', index=False)

# Part D: Data Manipulation

In [43]:
#The management wants additional information for reporting.

In [44]:
#1. Create a new column Family_Size .
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1

In [45]:
#2. Create a new column Total_Members .
df['Total_Members'] = df['SibSp'] + df['Parch'] + 1

In [46]:
#3. Create Fare_Per_Person
df['Fare_Per_Person'] = df['Ticket_Price'] / df['Total_Members']

In [47]:
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,Unknown,S,2,2,3.62500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C85,C,2,2,35.64165
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S,1,1,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,C123,S,2,2,26.55000
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,Unknown,S,1,1,8.05000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,13.0000,Unknown,S,1,1,13.00000
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,112053,30.0000,B42,S,1,1,30.00000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,23.4500,Unknown,S,4,4,5.86250
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,30.0000,C148,C,1,1,30.00000
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,7.7500,Unknown,Q,1,1,7.75000

In [48]:
# 4. Create a column named Passenger_Type .
# Child (<18)
# Adult (18–59)
# Senior (60+)

# df['Passenger_Type'] =np.where(
#     df['Age'] < 18, "Child",
#     np.where((df['Age']>=18) &(df['Age']<=59), 'Adult','Senior'  )
# )

def age_cate(Age):
    if pd.isnull(Age):
        return 'known'
    elif Age <18:
        return 'Child'
    elif Age <60:
        return 'Adult'
    else :
        return 'Senior'

df['Passenger_type'] = df['Age'].apply(age_cate)

In [49]:
df[df['Passenger_type'] == 'Child']

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
7,8,0,3,"Palsson, Master. Gosta Leonard",Male,2.0,3,1,349909,21.0750,Unknown,S,5,5,4.215000,Child
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Female,14.0,1,0,237736,30.0708,Unknown,C,2,2,15.035400,Child
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",Female,4.0,1,1,PP 9549,16.7000,G6,S,3,3,5.566667,Child
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",Female,14.0,0,0,350406,7.8542,Unknown,S,1,1,7.854200,Child
16,17,0,3,"Rice, Master. Eugene",Male,2.0,4,1,382652,29.1250,Unknown,Q,6,6,4.854167,Child
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",Male,4.0,4,2,347082,31.2750,Unknown,S,7,7,4.467857,Child
852,853,0,3,"Boulos, Miss. Nourelain",Female,9.0,1,1,2678,15.2458,Unknown,C,3,3,5.081933,Child
853,854,1,1,"Lines, Miss. Mary Conover",Female,16.0,0,1,PC 17592,39.4000,D28,S,2,2,19.700000,Child
869,870,1,3,"Johnson, Master. Harold Theodor",Male,4.0,1,1,347742,11.1333,Unknown,S,3,3,3.711100,Child
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",Female,15.0,0,0,2667,7.2250,Unknown,C,1,1,7.225000,Child

In [50]:
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.2500,Unknown,S,2,2,3.62500,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,71.2833,C85,C,2,2,35.64165,Adult
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S,1,1,7.92500,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,53.1000,C123,S,2,2,26.55000,Adult
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.0500,Unknown,S,1,1,8.05000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,13.0000,Unknown,S,1,1,13.00000,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,112053,30.0000,B42,S,1,1,30.00000,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,23.4500,Unknown,S,4,4,5.86250,known
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,30.0000,C148,C,1,1,30.00000,Adult
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,7.7500,Unknown,Q,1,1,7.75000,Adult

In [51]:
# 5. Increase all ticket prices by 10%.
df['Ticket_Price'] = df['Ticket_Price']*1.10

In [52]:
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.97500,Unknown,S,2,2,3.62500,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,78.41163,C85,C,2,2,35.64165,Adult
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,8.71750,Unknown,S,1,1,7.92500,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,58.41000,C123,S,2,2,26.55000,Adult
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.85500,Unknown,S,1,1,8.05000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,14.30000,Unknown,S,1,1,13.00000,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,112053,33.00000,B42,S,1,1,30.00000,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,25.79500,Unknown,S,4,4,5.86250,known
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,33.00000,C148,C,1,1,30.00000,Adult
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,8.52500,Unknown,Q,1,1,7.75000,Adult

In [53]:
# 6. Give an additional 5% increase only to First Class passengers.
df['Ticket_Price'] = np.where(df['Passenger_Class'] == 1,df['Ticket_Price']*1.05, df['Ticket_Price'])

In [54]:
# df.loc[df['Passenger_Class']==1,'Ticket_Price'] *= 1.05

In [55]:
df

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,A/5 21171,7.975000,Unknown,S,2,2,3.62500,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,PC 17599,82.332211,C85,C,2,2,35.64165,Adult
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,STON/O2. 3101282,8.717500,Unknown,S,1,1,7.92500,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,113803,61.330500,C123,S,2,2,26.55000,Adult
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,373450,8.855000,Unknown,S,1,1,8.05000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,211536,14.300000,Unknown,S,1,1,13.00000,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,112053,34.650000,B42,S,1,1,30.00000,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,25.795000,Unknown,S,4,4,5.86250,known
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,111369,34.650000,C148,C,1,1,30.00000,Adult
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,370376,8.525000,Unknown,Q,1,1,7.75000,Adult

In [56]:
#7. Delete the Ticket column.
df.drop('Ticket',axis =1)

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
0,1,0,3,"Braund, Mr. Owen Harris",Male,22.0,1,0,7.975000,Unknown,S,2,2,3.62500,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,1,0,82.332211,C85,C,2,2,35.64165,Adult
2,3,1,3,"Heikkinen, Miss. Laina",Female,26.0,0,0,8.717500,Unknown,S,1,1,7.92500,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Female,35.0,1,0,61.330500,C123,S,2,2,26.55000,Adult
4,5,0,3,"Allen, Mr. William Henry",Male,35.0,0,0,8.855000,Unknown,S,1,1,8.05000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Male,27.0,0,0,14.300000,Unknown,S,1,1,13.00000,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",Female,19.0,0,0,34.650000,B42,S,1,1,30.00000,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,25.795000,Unknown,S,4,4,5.86250,known
889,890,1,1,"Behr, Mr. Karl Howell",Male,26.0,0,0,34.650000,C148,C,1,1,30.00000,Adult
890,891,0,3,"Dooley, Mr. Patrick",Male,32.0,0,0,8.525000,Unknown,Q,1,1,7.75000,Adult

In [57]:
#8. Sort passengers by ticket price (highest first).
df.sort_values(by = 'Ticket_Price',ascending = False).head(1)

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
258,259,1,1,"Ward, Miss. Anna",Female,35.0,0,0,PC 17755,591.740226,Unknown,C,1,1,512.3292,Adult

In [58]:
# 9. Sort passengers by age (youngest first).
df.sort_values(by ='Age',ascending = True)

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
803,804,1,3,"Thomas, Master. Assad Alexander",Male,0.42,0,1,2625,9.36837,Unknown,C,2,2,4.258350,Child
755,756,1,2,"Hamalainen, Master. Viljo",Male,0.67,1,1,250649,15.95000,Unknown,S,3,3,4.833333,Child
644,645,1,3,"Baclini, Miss. Eugenie",Female,0.75,2,1,2666,21.18413,Unknown,C,4,4,4.814575,Child
469,470,1,3,"Baclini, Miss. Helene Barbara",Female,0.75,2,1,2666,21.18413,Unknown,C,4,4,4.814575,Child
78,79,1,2,"Caldwell, Master. Alden Gates",Male,0.83,0,2,248738,31.90000,Unknown,S,3,3,9.666667,Child
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",Male,NaN,0,0,2629,7.95212,Unknown,C,1,1,7.229200,known
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",Female,NaN,8,2,CA. 2343,76.50500,Unknown,S,11,11,6.322727,known
868,869,0,3,"van Melkebeke, Mr. Philemon",Male,NaN,0,0,345777,10.45000,Unknown,S,1,1,9.500000,known
878,879,0,3,"Laleff, Mr. Kristo",Male,NaN,0,0,349217,8.68538,Unknown,S,1,1,7.895800,known
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Female,NaN,1,2,W./C. 6607,25.79500,Unknown,S,4,4,5.862500,known

In [59]:
# 10. Sort by Passenger Class and Ticket Price.
df.sort_values(by =['Passenger_Class','Ticket_Price'])

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
263,264,0,1,"Harrison, Mr. William",Male,40.0,0,0,112059,0.000,B94,S,1,1,0.000000,Adult
633,634,0,1,"Parr, Mr. William Henry Marsh",Male,NaN,0,0,112052,0.000,Unknown,S,1,1,0.000000,known
806,807,0,1,"Andrews, Mr. Thomas Jr",Male,39.0,0,0,112050,0.000,A36,S,1,1,0.000000,Adult
815,816,0,1,"Fry, Mr. Richard",Male,NaN,0,0,112058,0.000,B102,S,1,1,0.000000,known
822,823,0,1,"Reuchlin, Jonkheer. John George",Male,38.0,0,0,19972,0.000,Unknown,S,1,1,0.000000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,202,0,3,"Sage, Mr. Frederick",Male,NaN,8,2,CA. 2343,76.505,Unknown,S,11,11,6.322727,known
324,325,0,3,"Sage, Mr. George John Jr",Male,NaN,8,2,CA. 2343,76.505,Unknown,S,11,11,6.322727,known
792,793,0,3,"Sage, Miss. Stella Anna",Female,NaN,8,2,CA. 2343,76.505,Unknown,S,11,11,6.322727,known
846,847,0,3,"Sage, Mr. Douglas Bullen",Male,NaN,8,2,CA. 2343,76.505,Unknown,S,11,11,6.322727,known
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",Female,NaN,8,2,CA. 2343,76.505,Unknown,S,11,11,6.322727,known

# Part E: String Operations

In [60]:
# The customer service department wants standardized passenger names.
# 1. Convert all passenger names to uppercase.
df['Name'] = df['Name'].str.upper()

In [61]:
# 2. Convert all passenger names to lowercase.
df['Name'] = df['Name'].str.lower()

In [62]:
# 3. Find all passengers whose names contain "Mr"
df[df['Name'].str.contains('Mr.',case = False)]

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
0,1,0,3,"braund, mr. owen harris",Male,22.0,1,0,A/5 21171,7.975000,Unknown,S,2,2,3.625000,Adult
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",Female,38.0,1,0,PC 17599,82.332211,C85,C,2,2,35.641650,Adult
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",Female,35.0,1,0,113803,61.330500,C123,S,2,2,26.550000,Adult
4,5,0,3,"allen, mr. william henry",Male,35.0,0,0,373450,8.855000,Unknown,S,1,1,8.050000,Adult
5,6,0,3,"moran, mr. james",Male,NaN,0,0,330877,9.304130,Unknown,Q,1,1,8.458300,known
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,884,0,2,"banfield, mr. frederick james",Male,28.0,0,0,C.A./SOTON 34068,11.550000,Unknown,S,1,1,10.500000,Adult
884,885,0,3,"sutehall, mr. henry jr",Male,25.0,0,0,SOTON/OQ 392076,7.755000,Unknown,S,1,1,7.050000,Adult
885,886,0,3,"rice, mrs. william (margaret norton)",Female,39.0,0,5,382652,32.037500,Unknown,Q,6,6,4.854167,Adult
889,890,1,1,"behr, mr. karl howell",Male,26.0,0,0,111369,34.650000,C148,C,1,1,30.000000,Adult
890,891,0,3,"dooley, mr. patrick",Male,32.0,0,0,370376,8.525000,Unknown,Q,1,1,7.750000,Adult

In [63]:
# 4. Find all passengers whose names contain "Mrs" .
df[df['Name'].str.contains('Mrs.',case = False)]

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",Female,38.0,1,0,PC 17599,82.332211,C85,C,2,2,35.641650,Adult
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",Female,35.0,1,0,113803,61.330500,C123,S,2,2,26.550000,Adult
8,9,1,3,"johnson, mrs. oscar w (elisabeth vilhelmina berg)",Female,27.0,0,2,347742,12.246630,Unknown,S,3,3,3.711100,Adult
9,10,1,2,"nasser, mrs. nicholas (adele achem)",Female,14.0,1,0,237736,33.077880,Unknown,C,2,2,15.035400,Child
15,16,1,2,"hewlett, mrs. (mary d kingcome)",Female,55.0,0,0,248706,17.600000,Unknown,S,1,1,16.000000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"beckwith, mrs. richard leonard (sallie monypeny)",Female,47.0,1,1,11751,60.700101,D35,S,3,3,17.518067,Adult
874,875,1,2,"abelson, mrs. samuel (hannah wizosky)",Female,28.0,1,0,P/PP 3381,26.400000,Unknown,C,2,2,12.000000,Adult
879,880,1,1,"potter, mrs. thomas jr (lily alexenia wilson)",Female,56.0,0,1,11767,96.047837,C50,C,2,2,41.579150,Adult
880,881,1,2,"shelley, mrs. william (imanita parrish hall)",Female,25.0,0,1,230433,28.600000,Unknown,S,2,2,13.000000,Adult
885,886,0,3,"rice, mrs. william (margaret norton)",Female,39.0,0,5,382652,32.037500,Unknown,Q,6,6,4.854167,Adult

In [64]:
# 5. Find all passengers whose names contain "Miss" .
df[df['Name'].str.contains('Miss',case = False)]

,PassengerId,Survived,Passenger_Class,Name,Sex,Age,SibSp,Parch,Ticket,Ticket_Price,Cabin,Embarked,Family_Size,Total_Members,Fare_Per_Person,Passenger_type
2,3,1,3,"heikkinen, miss. laina",Female,26.0,0,0,STON/O2. 3101282,8.71750,Unknown,S,1,1,7.925000,Adult
10,11,1,3,"sandstrom, miss. marguerite rut",Female,4.0,1,1,PP 9549,18.37000,G6,S,3,3,5.566667,Child
11,12,1,1,"bonnell, miss. elizabeth",Female,58.0,0,0,113783,30.66525,C103,S,1,1,26.550000,Adult
14,15,0,3,"vestrom, miss. hulda amanda adolfina",Female,14.0,0,0,350406,8.63962,Unknown,S,1,1,7.854200,Child
22,23,1,3,"mcgowan, miss. anna ""annie""",Female,15.0,0,0,330923,8.83212,Unknown,Q,1,1,8.029200,Child
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,867,1,2,"duran y more, miss. asuncion",Female,27.0,1,0,SC/PARIS 2149,15.24413,Unknown,C,2,2,6.929150,Adult
875,876,1,3,"najib, miss. adele kiamie ""jane""",Female,15.0,0,0,2667,7.94750,Unknown,C,1,1,7.225000,Child
882,883,0,3,"dahlberg, miss. gerda ulrika",Female,22.0,0,0,7552,11.56837,Unknown,S,1,1,10.516700,Adult
887,888,1,1,"graham, miss. margaret edith",Female,19.0,0,0,112053,34.65000,B42,S,1,1,30.000000,Adult
888,889,0,3,"johnston, miss. catherine helen ""carrie""",Female,NaN,1,2,W./C. 6607,25.79500,Unknown,S,4,4,5.862500,known

In [65]:
# 6. Replace "Mr." with "Mister"
df['Name'] = df['Name'].str.replace('Mr.','Mister',case = False)

# Part F: Aggregation Functions

In [66]:
df = pd.read_csv('/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv')

In [67]:
# 1. Total fare collected.
df['Fare'].sum()

np.float64(28693.9493)

In [68]:
# 2. Average fare.
df['Fare'].mean()

np.float64(32.204207968574636)

In [69]:
# 3. Median fare.
df['Fare'].median()

14.4542

In [70]:
#4. Minimum fare.
df['Fare'].min()

0.0

In [71]:
# 5. Maximum Fare.
df['Fare'].max()

512.3292

In [72]:
# 6. Standard deviation of fare.
df['Fare'].std()

49.693428597180905

In [73]:
# 7. Count total passengers.
df['PassengerId'].count()

np.int64(891)

In [74]:
# 8. Average passenger age.
df['Age'].mean()

np.float64(29.69911764705882)

In [75]:
# 9. Highest ticket price.
df = df.rename(columns = {
    'Fare' :'Ticket_Price'
})
df['Ticket_Price'].max()

512.3292

In [76]:
# 10. Lowest ticket price.
df['Ticket_Price'].min()

0.0

# Part G: GroupBy Operations

In [77]:
df = pd.read_csv('/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv')

In [78]:
# 1. Count passengers in each passenger class.
df.groupby('Pclass')['PassengerId'].count()

Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

In [79]:
df.groupby('Pclass').size()

Pclass
1    216
2    184
3    491
dtype: int64

In [80]:
# 2. Count passengers by gender.
df.groupby('Sex').size()

Sex
female    314
male      577
dtype: int64

In [81]:
# 3. Calculate average fare by passenger class.
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [82]:
# 4. Calculate average age by passenger class.
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [83]:
#5. Calculate maximum fare by passenger class.
df.groupby("Pclass")['Fare'].max()

Pclass
1    512.3292
2     73.5000
3     69.5500
Name: Fare, dtype: float64

In [84]:
# 6. Calculate minimum fare by passenger class.
df.groupby('Pclass')['Fare'].min()

Pclass
1    0.0
2    0.0
3    0.0
Name: Fare, dtype: float64

In [85]:
#7. Calculate total fare collected from each passenger class.
df.groupby('Pclass')['Fare'].sum()

Pclass
1    18177.4125
2     3801.8417
3     6714.6951
Name: Fare, dtype: float64

In [86]:
# 8. Find survival count by gender.
df.groupby('Sex')['Survived'].size()

Sex
female    314
male      577
Name: Survived, dtype: int64

In [87]:
#9. Find average fare by gender.
df.groupby('Sex')['Fare'].mean()

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [88]:
# # 10. Generate a report showing:
# Count
# Mean
# Median
# Minimum
# Maximum
# Standard Deviation
#for Fare grouped by Passenger Class.
df.groupby('Pclass')['Fare'].agg(['count','mean','median','min','max','std'])

        count       mean   median  min       max        std
Pclass
1         216  84.154687  60.2875  0.0  512.3292  78.380373
2         184  20.662183  14.2500  0.0   73.5000  13.417399
3         491  13.675550   8.0500  0.0   69.5500  11.778142

# Part H: Merge Operations

In [89]:
# Passenger Insurance

insurance = pd.DataFrame({
"PassengerId":[1,2,3,5,8,900],
"Policy":["Gold","Silver","Gold","Premium","Silver","Gold"]
})

# Passenger Meal Preference

meal = pd.DataFrame({
"PassengerId":[1,2,4,5,7,900],
"Meal":["Veg","Non-Veg","Veg","Veg","Non-Veg","Veg"]
})

In [90]:
#1. Perform an Inner Merge between Titanic and Insurance.
inner = pd.merge(
    df,
    insurance,
    on ='PassengerId',
    how ='right'
)
inner

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Policy
0,1,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S,Gold
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C,Silver
2,3,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S,Gold
3,5,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S,Premium
4,8,0.0,3.0,"Palsson, Master. Gosta Leonard",male,2.0,3.0,1.0,349909,21.0750,NaN,S,Silver
5,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gold

In [91]:
# 2. Perform a Left Merge between Titanic and Insurance.
left = pd.merge(
    df,
    insurance,
    on ='PassengerId',
    how ='left'
)
left

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Policy
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Gold
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Silver
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Gold
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Premium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [92]:
# 3. Perform a Right Merge between Titanic and Insurance.
right = pd.merge(
    df,
    insurance,
    on ='PassengerId',
    how ='right'
)
right

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Policy
0,1,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S,Gold
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C,Silver
2,3,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S,Gold
3,5,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S,Premium
4,8,0.0,3.0,"Palsson, Master. Gosta Leonard",male,2.0,3.0,1.0,349909,21.0750,NaN,S,Silver
5,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gold

In [93]:
df.isna().sum()
df.drop(columns ='Cabin')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [94]:
#4. Perform an Outer Merge between Titanic and Insurance.
outer = pd.merge(
    df,
    insurance,
    on ='PassengerId',
    how ='outer'
)
outer

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Policy
0,1,0.0,3.0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,NaN,S,Gold
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,C85,C,Silver
2,3,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,NaN,S,Gold
3,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,C123,S,NaN
4,5,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,NaN,S,Premium
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,1.0,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30.0000,B42,S,NaN
888,889,0.0,3.0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1.0,2.0,W./C. 6607,23.4500,NaN,S,NaN
889,890,1.0,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30.0000,C148,C,NaN
890,891,0.0,3.0,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.7500,NaN,Q,NaN
891,900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gold

In [95]:
#5. Identify passengers who do not have insurance.
no_insurance = left[left['Policy'].isna()]
no_insurance

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Policy
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,NaN
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,NaN
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,NaN
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN

In [96]:
# 6. Identify insurance records that do not have matching passengers.

In [97]:
#7. Merge Passenger, Insurance, and Meal datasets into one final DataFrame.
final_df = pd.merge(
    df,
    insurance,
    on ='PassengerId',
    how ='left'
)
final_df = pd.merge(
    final_df,
    meal,
    on ='PassengerId',
    how ='left'
)

In [98]:
final_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Policy,Meal
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Gold,Veg
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Silver,Non-Veg
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Gold,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN,Veg
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Premium,Veg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN,NaN
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN,NaN

In [99]:
# nested merge
final_df = pd.merge(
    pd.merge(df,insurance,on ='PassengerId',how ='left'),
    meal,
    on ='PassengerId',
    how ="left"
)
final_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Policy,Meal
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Gold,Veg
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Silver,Non-Veg
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Gold,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN,Veg
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Premium,Veg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,NaN,NaN
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,NaN,NaN
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,NaN,NaN
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,NaN,NaN

In [100]:
# 8. Replace missing insurance values with "Not Insured" .

left['Policy'].fillna('Not Insured',inplace =True)

/tmp/ipykernel_58/4136134957.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  left['Policy'].fillna('Not Insured',inplace =True)

In [101]:
final_df['Policy'].fillna('Not Insured',inplace =True)

/tmp/ipykernel_58/1962791278.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df['Policy'].fillna('Not Insured',inplace =True)

In [102]:
left.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Policy           0
dtype: int64

In [103]:
#9. Replace missing meal values with "Meal Not Selected" .
final_df['Meal'].isna().sum()

np.int64(886)

In [104]:
final_df['Meal'].fillna('Meal Not Selected',inplace =True)

/tmp/ipykernel_58/2619580258.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df['Meal'].fillna('Meal Not Selected',inplace =True)

In [105]:
final_df['Meal'].isna().sum()

np.int64(0)

In [106]:
final_df['Meal']

0                    Veg
1                Non-Veg
2      Meal Not Selected
3                    Veg
4                    Veg
             ...
886    Meal Not Selected
887    Meal Not Selected
888    Meal Not Selected
889    Meal Not Selected
890    Meal Not Selected
Name: Meal, Length: 891, dtype: object

In [107]:
# 10. Save the merged dataset as Passenger_Report.csv
final_df.to_csv('Passenger_Report.csv')

# Part I: Concatenation

In [108]:
# January Bookings

jan = pd.DataFrame({
"PassengerId":[1001,1002,1003],
"Passenger_Name":["Aman","Riya","Karan"]
})

# February Bookings

feb = pd.DataFrame({
"PassengerId":[1004,1005],
"Passenger_Name":["Neha","Rahul"]
})

# City Details

city = pd.DataFrame({
"City":["Delhi","Mumbai","Pune","Jaipur","Lucknow"]
})

In [109]:
# 1. Perform vertical concatenation of January and February bookings.
vartical = pd.concat([jan ,feb])
vartical

   PassengerId Passenger_Name
0         1001           Aman
1         1002           Riya
2         1003          Karan
0         1004           Neha
1         1005          Rahul

In [110]:
#2. Perform vertical concatenation using ignore_index=True .
vartical = pd.concat([jan,feb],ignore_index = True)
vartical

   PassengerId Passenger_Name
0         1001           Aman
1         1002           Riya
2         1003          Karan
3         1004           Neha
4         1005          Rahul

In [111]:
#3. Perform horizontal concatenation of bookings and city details.
horizontal = pd.concat([vartical,city],axis = 1)
horizontal

   PassengerId Passenger_Name     City
0         1001           Aman    Delhi
1         1002           Riya   Mumbai
2         1003          Karan     Pune
3         1004           Neha   Jaipur
4         1005          Rahul  Lucknow

In [112]:
#4. Display the final concatenated DataFrame.
horizontal

   PassengerId Passenger_Name     City
0         1001           Aman    Delhi
1         1002           Riya   Mumbai
2         1003          Karan     Pune
3         1004           Neha   Jaipur
4         1005          Rahul  Lucknow

In [113]:
# 5. Explain the difference between vertical and horizontal concatenation.
#ans in vartical  one dataframe is place bleow another dataframe and add rows only
#    but in horizontal one dataframe is place beside another dataframe and add columns.

# Part J: DateTime, Apply, Map & Feature Engineering

In [114]:
# Create a new column named Booking_Date containing random dates from the year 2024.
df = horizontal
df

   PassengerId Passenger_Name     City
0         1001           Aman    Delhi
1         1002           Riya   Mumbai
2         1003          Karan     Pune
3         1004           Neha   Jaipur
4         1005          Rahul  Lucknow

In [115]:
import pandas as pd
import numpy as np

np.random.seed(42)

df["Booking_Date"] = pd.to_datetime(
    np.random.choice(
        pd.date_range(start="2024-01-01", end="2024-12-31"),
        size=len(df)
    )
)

df

   PassengerId Passenger_Name     City Booking_Date
0         1001           Aman    Delhi   2024-04-12
1         1002           Riya   Mumbai   2024-12-14
2         1003          Karan     Pune   2024-09-27
3         1004           Neha   Jaipur   2024-04-16
4         1005          Rahul  Lucknow   2024-03-12

In [116]:
#1. Convert Booking_Date into datetime format.
df['Booking_Date'] = pd.to_datetime(df['Booking_Date'])
df['Booking_Date']

0   2024-04-12
1   2024-12-14
2   2024-09-27
3   2024-04-16
4   2024-03-12
Name: Booking_Date, dtype: datetime64[ns]

In [117]:
# 2. Extract:
# Year
# Month
# Day
# Month Name
# Day Name

df['Year'] =df['Booking_Date'].dt.year
df['Month']  =df['Booking_Date'].dt.month
df['Day'] =df['Booking_Date'].dt.day
df['Month_Name'] =df['Booking_Date'].dt.month_name()
df['day_Name'] =df['Booking_Date'].dt.day_name()
df

,PassengerId,Passenger_Name,City,Booking_Date,Year,Month,Day,Month_Name,day_Name
0,1001,Aman,Delhi,2024-04-12,2024,4,12,April,Friday
1,1002,Riya,Mumbai,2024-12-14,2024,12,14,December,Saturday
2,1003,Karan,Pune,2024-09-27,2024,9,27,September,Friday
3,1004,Neha,Jaipur,2024-04-16,2024,4,16,April,Tuesday
4,1005,Rahul,Lucknow,2024-03-12,2024,3,12,March,Tuesday

In [118]:
# 3. Create an Age_Group column using apply() .
import pandas as pd
df1 = pd.read_csv('/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv')

In [119]:
def age_group(Age):
    if pd.isnull(Age):
        return 'unknown'
    elif Age < 18:
        return "Child"
    elif Age < 60:
        return 'Adult'
    else:
        return 'Senior'

df1["Age_Group"] = df1['Age'].apply(age_group)
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,unknown
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult

In [120]:
# 4. Create a Gender_Code column using map() .
df1['Gender_Code'] = df1['Sex'].map({
    'male' : 0,
    'female' : 1 
})

In [121]:
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group,Gender_Code
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult,0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,unknown,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult,0

In [122]:
#5. Increase every value in a sample numeric DataFrame using applymap() .
df2 = pd.DataFrame({
    'StId': [101,108,140,120],
    'Age' : [12,17,19,20]
})
df2 = df2.applymap(lambda x : x*2)
df2

/tmp/ipykernel_58/1438268825.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df2 = df2.applymap(lambda x : x*2)

   StId  Age
0   202   24
1   216   34
2   280   38
3   240   40

In [123]:
# 6. Create a Premium_Passenger column using a lambda function.
#df3 = pd.read_csv('/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv')
df1['Premium_Passenger'] = df1['Pclass'].apply(lambda x: 'Yes' if x == 1 else 'No')
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group,Gender_Code,Premium_Passenger
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult,0,No
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,1,Yes
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,1,No
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,1,Yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult,0,No
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult,1,Yes
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,unknown,1,No
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult,0,Yes
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult,0,No

In [124]:
# 7. Create a Family_Size feature.
df1['Family_Size'] = df1['SibSp'] + df1['Parch'] + 1

In [125]:
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group,Gender_Code,Premium_Passenger,Family_Size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult,0,No,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,1,Yes,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,1,No,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,1,Yes,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult,0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult,0,No,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult,1,Yes,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,unknown,1,No,4
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult,0,Yes,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult,0,No,1

In [126]:
# 8. Create an Is_Alone feature.
df1[' Is_Alone'] = (df1['Family_Size'] == 1).astype(int)
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group,Gender_Code,Premium_Passenger,Family_Size,Is_Alone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult,0,No,2,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,1,Yes,2,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,1,No,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,1,Yes,2,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult,0,No,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult,0,No,1,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult,1,Yes,1,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,unknown,1,No,4,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult,0,Yes,1,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult,0,No,1,1

In [127]:
#9. Create a Fare_Per_Person feature.
df1['Fare_Per_Person'] =df1["Fare"] / df1['Family_Size']
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group,Gender_Code,Premium_Passenger,Family_Size,Is_Alone,Fare_Per_Person
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult,0,No,2,0,3.62500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,1,Yes,2,0,35.64165
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,1,No,1,1,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,1,Yes,2,0,26.55000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult,0,No,1,1,8.05000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult,0,No,1,1,13.00000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult,1,Yes,1,1,30.00000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,unknown,1,No,4,0,5.86250
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult,0,Yes,1,1,30.00000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult,0,No,1,1,7.75000

In [128]:
#10. Create a Fare_Category feature using bins.

In [129]:
df1['Fare_Category'] = pd.cut(
    df1['Fare'],
    bins=[0, 10, 25, 600],
    labels=['Low', 'Medium', 'High'],
    include_lowest=True
)

df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Group,Gender_Code,Premium_Passenger,Family_Size,Is_Alone,Fare_Per_Person,Fare_Category
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult,0,No,2,0,3.62500,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,1,Yes,2,0,35.64165,High
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,1,No,1,1,7.92500,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,1,Yes,2,0,26.55000,High
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult,0,No,1,1,8.05000,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult,0,No,1,1,13.00000,Medium
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult,1,Yes,1,1,30.00000,High
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,unknown,1,No,4,0,5.86250,Medium
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult,0,Yes,1,1,30.00000,High
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult,0,No,1,1,7.75000,Low

In [130]:
# 11. Display the final feature-engineered dataset.
print('first dateset\n',df)
print('second dataset\n',df1)
print('third dataset\n',df2)

first dateset
    PassengerId Passenger_Name     City Booking_Date  Year  Month  Day  \
0         1001           Aman    Delhi   2024-04-12  2024      4   12
1         1002           Riya   Mumbai   2024-12-14  2024     12   14
2         1003          Karan     Pune   2024-09-27  2024      9   27
3         1004           Neha   Jaipur   2024-04-16  2024      4   16
4         1005          Rahul  Lucknow   2024-03-12  2024      3   12

  Month_Name  day_Name
0      April    Friday
1   December  Saturday
2  September    Friday
3      April   Tuesday
4      March   Tuesday
second dataset
      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked Age_Group  Gender_Code  \
0        0         A/5 21171   7.2500   NaN        S     Adult            0
1        0          PC 17599  71.2833   C85        C     Adult            1
2        0  STON/O2. 3101282   7.9250   NaN        S     Adult            1
3        0            113803  53.1000  C123        S     Adult            1
4        0            373450   8.0500   NaN        S     Adult            0
..     ...               ...      ...   ...      ...       ...          ...
886      0            211536  13.0000   NaN        S     Adult            0
887      0            112053  30.0000   B42        S     Adult            1
888      2        W./C. 6607  23.4500   NaN        S   unknown            1
889      0            111369  30.0000  C148        C     Adult            0
890      0            370376   7.7500   NaN        Q     Adult            0

    Premium_Passenger  Family_Size   Is_Alone  Fare_Per_Person Fare_Category
0                  No            2          0          3.62500           Low
1                 Yes            2          0         35.64165          High
2                  No            1          1          7.92500           Low
3                 Yes            2          0         26.55000          High
4                  No            1          1          8.05000           Low
..                ...          ...        ...              ...           ...
886                No            1          1         13.00000        Medium
887               Yes            1          1         30.00000          High
888                No            4          0          5.86250        Medium
889               Yes            1          1         30.00000          High
890                No            1          1          7.75000           Low

[891 rows x 19 columns]
third dataset
    StId  Age
0   202   24
1   216   34
2   280   38
3   240   40

# Final Business Case Study

In [ ]:
# You are the Lead Data Analyst at the shipping company. Management requires a final analytical report.
# Your report should answer:

In [136]:
# 1. Total number of passengers.

df1.shape[0]

891

In [142]:
#2. Survival rate.
print((df1['Survived'].mean()*100).round(2),'%')

38.38 %

In [147]:
# 3. Passenger count by class.
df1['Pclass'].value_counts()
#df1.groupby('Pclass')['PassengerId'].count()

Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

In [148]:
# 4. Average age by passenger class.
df1.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [149]:
# 5. Average fare by passenger class.
df1.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [153]:
# 6. Top 10 passengers who paid the highest fare.
df1[['Name','Fare']].sort_values(by ='Fare', ascending = False).head(10)

                                                Name      Fare
679               Cardeza, Mr. Thomas Drake Martinez  512.3292
258                                 Ward, Miss. Anna  512.3292
737                           Lesurer, Mr. Gustave J  512.3292
88                        Fortune, Miss. Mabel Helen  263.0000
438                                Fortune, Mr. Mark  263.0000
341                   Fortune, Miss. Alice Elizabeth  263.0000
27                    Fortune, Mr. Charles Alexander  263.0000
742            Ryerson, Miss. Susan Parker "Suzette"  262.3750
311                       Ryerson, Miss. Emily Borie  262.3750
299  Baxter, Mrs. James (Helene DeLaudeniere Chaput)  247.5208

In [156]:
# 7. Gender-wise survival count.
df1.groupby('Sex')['Survived'].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [159]:
# 8. Number of solo travelers.
df1[df1['Family_Size'] == 1].shape[0]

537

In [173]:
# 9. Number of family travelers.
df1[df1[' Is_Alone'] == 0].shape[0]

354

In [175]:
# 10. Distribution of fare categories.

df1['Fare_Category'].value_counts()

Fare_Category
Low       336
High      334
Medium    221
Name: count, dtype: int64

In [177]:
#11. Number of premium passengers.
df1[df1['Premium_Passenger'] == 'Yes'].shape[0]

216

In [193]:
# 12. Missing value summary after cleaning.
df1.isnull().sum()

PassengerId          0
Survived             0
Pclass               0
Name                 0
Sex                  0
Age                  0
SibSp                0
Parch                0
Ticket               0
Fare                 0
Embarked             0
Age_Group            0
Gender_Code          0
Premium_Passenger    0
Family_Size          0
 Is_Alone            0
Fare_Per_Person      0
Fare_Category        0
dtype: int64

In [182]:
# 13. Create a final cleaned and feature-engineered dataset.
df1['Age'].fillna(df1['Age'].mean(),inplace =True)

/tmp/ipykernel_58/782372197.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Age'].fillna(df1['Age'].mean(),inplace =True)

In [185]:
df1.drop('Cabin',axis =1,inplace = True)

In [192]:
df1['Embarked'].fillna(df1['Embarked'].mode()[0],inplace = True)

In [196]:
final_df = df1.copy()

final_df.to_csv('final cleaned and feature-engineered dataset.csv',index = False)

In [197]:
# 14. Export the final dataset as Titanic_Final.csv
final_df.to_csv('Titanic_Final.csv',index =False)